Landing section changes
hasnatali1947/Portfolio pull request #5
Opened 2023-02-17 11:58 UTC by hasnatali1947

Did the following changes in the landing section
- Images added
- Adjusted margin and padding
- Renamed Files
- Replaced Name with my Name
- Nav bar Html and css changes

2023-02-17 12:51 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @hasnatali1947 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Kindly, make sure you changed the name of the project and the description 👍 

![section](https://user-images.githubusercontent.com/57408419/219657429-3521403d-009e-4dbf-a449-4fd1fe3ac0e4.jpg)


- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 12:51 UTC, joel-kalema commented on index.html
> +          </div>
Good job @hasnatali1947 😄, but make sure you update the styling of your headline section to better match the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=vByip9LCrbQjAJIk-0) as is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md#:~:text=Your%20website%20should%20look%20exactly%20like%20the%20design%20(e.g.%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20templates%20in%20Figma.). Kindly fix some font-size, margin, font weigh and color 👍

> | | Figma template | | Your project | |
> |-|---------|-|--------|-|
> | | <img width="226" alt="mobile 2 0" src="https://user-images.githubusercontent.com/57408419/219616755-cf131229-f222-4666-8d7e-1849ec48f9be.png"> | |![mobile](https://user-images.githubusercontent.com/57408419/219652618-c9f30922-95b4-4671-b3f2-f890f012c09d.jpg) | |

2023-02-17 14:28 UTC, OyePriscilla requested changes
Hi @hasnatali1947 👏, 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Linters passed ✔️
GitHub Flow observed ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [optional] Please ensure that your subsequent PRs, the commit messages are more descriptive; in imperative tense and capitalized. [Reference](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

- [optional] Please kindly add the missing headers in your README file (Future features and Show your support), this will enhance your repo professionalism. 👍 

- [optional] I think it will be nice if you can change your PR title to something more descriptive to this milestone 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 14:28 UTC, OyePriscilla commented on index.html
> +          </div>
- [ ] Please, we still need to work more on the typography (e.g. font, colors, images, text, margins) issues pinpointed by the previous reviewer, your text had overlaid the background-image as oppose what we have in figma design. Kindly ensure to reproduce what we have in figma design, this will really help a lot in the journey of software development; we need to always pay attention to details. Thanks. 👍 

> The `h1` text color is `#172B4D`

> The `p` text color is `#344563`

## Your Design

![DSC_7491](https://user-images.githubusercontent.com/103386183/219677621-8d4ab643-9327-4a47-b5c6-fe539abfbfc0.JPG)

2023-02-17 14:28 UTC, OyePriscilla commented on README.md
> +# 📖 About <a name="about-project"></a>
- [] Awesome changing the name of the project as requested, but can you please make it more descriptive (maybe **Portfolio**)? This will make your repo looks more professional. 👍

2023-02-17 15:41 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @hasnatali1947  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️professional PR👍 
✔️professional README👍 
✔️No Linter Errors👍 

## Optional Requirements

- [ ] I think it would be better to put all your assets or images in an **image folder** to make your root directory clean and kindly don't forget to update the image links 😉😉 


### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 12:43 UTC, aamirkhan2478 reviewed
Hi @hasnatali1947 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle:  :red_circle: 

You have submitted a project, that has been approved please merge this branch and create a new branch and implement your `Portfolio: finish mobile version`  code and then create a new PR and then submit this new PR for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-18 13:50 UTC, merged