added media query and finish the project
hasnatali1947/Portfolio pull request #8
Opened 2023-02-22 10:59 UTC by hasnatali1947

- Added media query
- Finish all project

2023-02-22 13:14 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @hasnatali1947 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 13:14 UTC, joel-kalema commented on index.html
>      <main>
Great work @hasnatali1947 working on your desktop version 😃, but you still need to fix some parts:

- [ ] Kindly make sure you fixed your `nav` 😃 , please remove the icon in desktop version. As we can see the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=noHceN5fZjbUZpNo-0) , the icon is displayed on the mobile version only, but on the desktop version we are displaying the links to your `Portofolio`, `About` and `Contact` 
- [ ] Kind make sure you fixed the `background image` to replicate the design as much as possible as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#:~:text=You%20must%20replicate%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20info%20from%20the%20Figma%20templates.). Also your `icon's margins`, when the `height` of the screen is less than `700px` it's not fixed well. I know you worked with a big screen that is why you can't see it, but if another person with a different screen try to run your project, it gives that error, kindly fix it 👍 
 

### Figma
![good](https://user-images.githubusercontent.com/57408419/220611921-7a2e56d3-5a22-4a6a-908d-031cf5d7833f.jpg)

### Your design
![desk error](https://user-images.githubusercontent.com/57408419/220613510-3e523663-d092-457a-8eb8-0b6f7a48deac.jpg)

2023-02-22 13:14 UTC, joel-kalema commented on index.html
> -            </a>
- [ ] Great work @hasnatali1947 working on your desktop version 😃, but make sure you fixed `margin` to replicate the design as much as possible as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#:~:text=You%20must%20replicate%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20info%20from%20the%20Figma%20templates.). Kindly don't forget to fix you the `style` when we `hover` your `section` and `button` 👍  
### Figma
![project good](https://user-images.githubusercontent.com/57408419/220624072-8bd8ac70-d0de-4754-8357-734e49d380b4.jpg)
### Your design
![project error](https://user-images.githubusercontent.com/57408419/220624098-4b21affa-5862-4871-8a80-47f2b3f5f49d.jpg)

- [ ] Also make sure you fixed the section `width` to to replicate the design as much as possible as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#:~:text=You%20must%20replicate%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20info%20from%20the%20Figma%20templates.).

### Figma
![about good](https://user-images.githubusercontent.com/57408419/220626941-03528fa1-fe26-492c-a2f2-7791da03082b.jpg)
### Your design
![about error](https://user-images.githubusercontent.com/57408419/220626983-2fc33857-2537-4a82-8c73-1353b080be93.jpg)


- [ ] Please, fix the `background image`  to to replicate the design as much as possible as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#:~:text=You%20must%20replicate%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20info%20from%20the%20Figma%20templates.).

### Figma
![contact good](https://user-images.githubusercontent.com/57408419/220628212-801b9324-78b5-431c-b900-41f6219dbfe2.jpg)
### Your design
![contact error](https://user-images.githubusercontent.com/57408419/220628233-21fc1ca9-4846-4ee7-beac-116bfaf3e535.jpg)

2023-02-23 10:55 UTC, mckent05 approved these changes
Hi @hasnatali1947, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Your portfolio looks good 👍 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 10:55 UTC, mckent05 commented on index.html
> +</body>
**OPTIONAL** - I see that you have two sections of HTML, one for the mobile version and another for the desktop version, this is not good practice. You are required to have just one part and use CSS (media-queries) to make them responsive for both mobile and desktop. Please I strongly advise you to fix this 🙏

2023-02-24 07:31 UTC, merged